apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  annotations:
    kubernetes.io/service-account.name: ${namespace}-sa
  name: ${namespace}-sa-token
  namespace: ${namespace}
  labels:
    app.kubernetes.io/name: ${namespace}-sa-token
data: {}