apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${namespace}-sa
  namespace: ${namespace}
  labels:
    app.kubernetes.io/name: ${namespace}-sa
automountServiceAccountToken: false
#secrets:
#  - name: ${namespace}-sa-token